[package]
name = "rxbanish"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.81"
clap = { version = "4.5.4", features = ["derive", "wrap_help"] }
xcb = { version = "1.3.0", features = ["xfixes", "xinput", "sync"] }
